version: "3.7"
services:
  app:
    build: ./docker/php
    image: azatora_app
    volumes:
      - ./contents:/home/azatora/contents
    links:
      - mysql

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./contents:/home/azatora/contents
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /home/azatora/contents
    links:
      - app
      - mysql

  mysql:
    build: ./docker/mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_azatora_db
      MYSQL_USER: azatora
      MYSQL_PASSWORD: azatora
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-store:
